### PR TITLE
Backpropagation Python Implementation

### PR DESCRIPTION
**Pull request by Bazarovay**
### Changelog
-------------------------------------------------------
- Add explanatory comments
- Implement backpropagation *_in progress_*

### CODE REVIEW

**Comment by syedmohsinbukhari** [comment]
Keep it up but please make sure that we are not just copy pasting. Or are we?

**Comment by Bazarovay** [comment]
Well, I did go over the chapter and summarized it in the description section before _copy pasting_ it. Now backpropagation is no NEAT paper but you might still agree that it will take me a little more time before I can do my own implementation from scratch.

**Comment by Bazarovay** [comment]
@syedmohsinbukhari SGD added in today's push.

**Review by syedmohsinbukhari — COMMENTED** [review]
looks good.

**Comment by Bazarovay** [comment]
Added cost functions. Sorry, I need one more day on this task. I apologize.

**Comment by syedmohsinbukhari** [comment]
> Added cost functions. Sorry, I need one more day on this task. I apologize.

That's fine. We both need another day.

**Comment by syedmohsinbukhari** [comment]
where is today's push?

**Comment by syedmohsinbukhari** [comment]
Please update on progress regarding this.

**Comment by syedmohsinbukhari** [comment]
Please either close or complete

### WILL BE CLOSED IN 2 DAYS

**Comment by Bazarovay** [comment]
Closing

**Pull request closed without merging**
