### PR TITLE
Genetic Algo example

### PR DESCRIPTION
**Pull request by Bazarovay**
Change log
----------------------------------------------
- Added genetic algorithm implementation in examples/genetic_algo_demo.py
- Fixed the spelling mistake
- Requirements & MAKEFILE added

### CODE REVIEW

**Comment by Bazarovay** [comment]
Please review my pull request

**Comment by Bazarovay** [comment]
Reminder.

**Review by syedmohsinbukhari — CHANGES_REQUESTED** [review]
### Points to consider
----------------------------------------
- The example added does not use our library.
- All the examples in the examples folder should use our own library.
- Please make a new directory for such experiments.
- Please name the above mentioned directory "experiments". We can remove this later before our releases.
- There are no test cases.
- Otherwise, seems good.

**Comment by Bazarovay** [comment]
Updated. Added test cases and created experiments directory.
need to integrate readthedocs and travis for documentation and running tests

**Review by syedmohsinbukhari — CHANGES_REQUESTED** [review]
The Python version in .readthedocs.yml and .travis.yml is different.

**Comment by syedmohsinbukhari** [comment]
looks good now

**Review by syedmohsinbukhari — APPROVED** [review]

**Pull request merged**
