### PR TITLE
Bazarovay/neural_model

### PR DESCRIPTION
**Pull request by Bazarovay**
### Change log
-------------------------------------------------
- Refactored genetic programming experiment file

### CODE REVIEW

**Comment by syedmohsinbukhari** [comment]
please put me as an assignee for next Pull Requests

**Review by syedmohsinbukhari — CHANGES_REQUESTED** [review]
Please write some test cases for back propagation.

**Comment by syedmohsinbukhari** [comment]
this is fail. failing tests. please either close of fix.

### IT WILL BE CLOSED IN 2 DAYS

**Comment by Bazarovay** [comment]
Test cases have been added, and the travis tests have passed now. Apologies for the delay

**Comment by Bazarovay** [comment]
Sphinx setup added

**Review by syedmohsinbukhari — APPROVED** [review]
Approved so that we can move on to NEAT.

**Pull request merged**
