### PR TITLE
Resources & Checklist added

### PR DESCRIPTION
**Pull request by Bazarovay**
### Change Log
---------------------------------------------------------
- Resources added (Paper, introductory video etc)
- Checklist added

### CODE REVIEW

**Review by syedmohsinbukhari — COMMENTED** [review]
Please remove the spelling mistake in the To Do section. Or is it really "Genetric algos"?

**Comment by syedmohsinbukhari** [comment]
Also, in the Change logs please mention the file in which you are editing.

**Review by syedmohsinbukhari — CHANGES_REQUESTED** [review]
Please make the changes in typos/spelling mistakes. Also please review again for other spelling mistakes.

**Comment by Bazarovay** [comment]
Changes have been made in the other pull request

**Pull request closed without merging**
